GOOGLE_API_KEY = "<google_api_key>"
DB_CONN_STR = "<connection_string_for_couchbase_cluster>"
DB_USERNAME = "<username_for_couchbase_cluster>"
DB_PASSWORD = "<password_for_couchbase_cluster>"
DB_BUCKET = "imdb"
DB_SCOPE = "_default"
DB_COLLECTION = "_default"
INDEX_NAME = "imdb-index"
EMBEDDING_MODEL = "models/text-embedding-004"
